[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["javac -encoding UTF-8 CountrySearchServer.java"]

[phases.start]
cmd = "java CountrySearchServer"

[start]
includeFiles = ["countries.csv"]
